services:
  postgres_db:
    image: postgres:18-alpine
    container_name: mi_postgres_18
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todolist_db
    ports:
      - "5432:5432"
    volumes:
      - pg18_data:/var/lib/postgresql/data

  django_backend:
    build: ./backend
    container_name: mi_django_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      POSTGRES_DB: todolist_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    depends_on:
      - postgres_db
    volumes:
      - ./backend:/app

volumes:
  pg18_data: