services:
  postgres_db:
    image: postgres:18-alpine
    container_name: mi_postgres_18
    restart: always
    environment:
      POSTGRES_USER: admin           # El usuario para tu DB
      POSTGRES_PASSWORD: admin       # La contraseña para tu DB
      POSTGRES_DB: todolist_db       # El nombre de la base de datos
    ports:
      - "5432:5432"
    volumes:
      - pg18_data:/var/lib/postgresql/data

volumes:
  pg18_data:
